version: '3'
services:

  db:
    image: postgres:14.2
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "--host=db", "--username=postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    user: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  redis:
    image: "redis:alpine"
    expose:
      - "6379"
    volumes:
      - redis-data:/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/bin/bash", "/code/compose-start.sh"]
    image: ksvotes:v3ksvotesorg-web
    depends_on:
      - db
      - redis
    env_file:
      - .env
    # init: true
    ports:
      - "8000:8000"

volumes:
  postgres-data:
  redis-data:
