# -*- coding: utf-8 -*-
# Generated by Django 4.0.4 on 2022-05-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ksvotes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrant",
            name="ab_completed_at",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="registrant",
            name="ab_identification_found",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="registrant",
            name="ab_permanent",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="registrant",
            name="addr_lookup_complete",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="registrant",
            name="dob_year",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="registrant",
            name="identification_found",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="registrant",
            name="is_citizen",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="registrant",
            name="is_eighteen",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="registrant",
            name="redacted_at",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="registrant",
            name="reg_found",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="registrant",
            name="reg_lookup_complete",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="registrant",
            name="vr_completed_at",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
