# -*- coding: utf-8 -*-
# Generated by Django 4.0.4 on 2022-05-10 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ksvotes", "0002_alter_registrant_ab_completed_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clerk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("county", models.CharField(max_length=255)),
                ("officer", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=255)),
                ("fax", models.CharField(max_length=255)),
                ("address1", models.CharField(max_length=255)),
                ("address2", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("state", models.CharField(default="KS", max_length=255)),
                ("zip", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
