# -*- coding: utf-8 -*-
# Generated by Django 4.0.4 on 2022-05-11 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ksvotes", "0003_clerk"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZIPCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("zipcode", models.CharField(max_length=10, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ZIPCodeCounty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("voter_count", models.IntegerField(null=True)),
                (
                    "clerk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ksvotes.clerk"
                    ),
                ),
                (
                    "zipcode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ksvotes.zipcode",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="zipcode",
            name="counties",
            field=models.ManyToManyField(
                through="ksvotes.ZIPCodeCounty", to="ksvotes.clerk"
            ),
        ),
        migrations.AddConstraint(
            model_name="zipcodecounty",
            constraint=models.UniqueConstraint(
                fields=("clerk_id", "zipcode_id"), name="clerk_zipcode_unique"
            ),
        ),
    ]
