# -*- coding: utf-8 -*-
# Generated by Django 4.0.4 on 2022-05-28 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ksvotes", "0004_zipcode_zipcodecounty_zipcode_counties_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registrant",
            options={"ordering": ["-id"]},
        ),
        migrations.RemoveField(
            model_name="zipcode",
            name="counties",
        ),
        migrations.AddField(
            model_name="zipcode",
            name="clerks",
            field=models.ManyToManyField(
                through="ksvotes.ZIPCodeCounty", to="ksvotes.clerk"
            ),
        ),
        migrations.AlterField(
            model_name="zipcodecounty",
            name="zipcode",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="counties",
                to="ksvotes.zipcode",
            ),
        ),
    ]
