# -*- coding: utf-8 -*-
# Generated by Django 4.0.8 on 2022-10-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ksvotes", "0006_registrant_user_agent"),
    ]

    operations = [
        migrations.CreateModel(
            name="EarlyVotingLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("election_date", models.DateField()),
                ("polling_place_id", models.IntegerField(null=True)),
                ("polling_place_name", models.CharField(max_length=255, null=True)),
                ("address1", models.CharField(max_length=255)),
                ("address2", models.CharField(max_length=255, null=True)),
                ("city", models.CharField(max_length=255)),
                ("state", models.CharField(default="KS", max_length=255)),
                ("zipcode", models.CharField(max_length=10)),
                ("opens_at", models.DateTimeField(default=None, null=True)),
                ("closes_at", models.DateTimeField(default=None, null=True)),
                ("dropoff_type", models.CharField(max_length=255, null=True)),
                ("ballot_drop_off", models.BooleanField(default=None, null=True)),
                ("county", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name="earlyvotinglocation",
            index=models.Index(
                fields=["zipcode"], name="ksvotes_ear_zipcode_3ae3a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="earlyvotinglocation",
            index=models.Index(fields=["county"], name="ksvotes_ear_county_254fc0_idx"),
        ),
    ]
