# -*- coding: utf-8 -*-
# Generated by Django 4.0.8 on 2022-10-27 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ksvotes", "0007_earlyvotinglocation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EarlyVotingLocationHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("opens_at", models.DateTimeField(default=None, null=True)),
                ("closes_at", models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="earlyvotinglocation",
            name="closes_at",
        ),
        migrations.RemoveField(
            model_name="earlyvotinglocation",
            name="opens_at",
        ),
        migrations.AddIndex(
            model_name="earlyvotinglocation",
            index=models.Index(
                fields=["polling_place_id"], name="ksvotes_ear_polling_6a2d39_idx"
            ),
        ),
        migrations.AddField(
            model_name="earlyvotinglocationhours",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ksvotes.earlyvotinglocation",
            ),
        ),
        migrations.AddIndex(
            model_name="earlyvotinglocationhours",
            index=models.Index(
                fields=["location"], name="ksvotes_ear_locatio_0d6573_idx"
            ),
        ),
    ]
