# -*- coding: utf-8 -*-
# Generated by Django 4.2.30 on 2026-07-12 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ksvotes", "0008_earlyvotinglocationhours_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrant",
            name="user_agent",
            field=models.CharField(null=True),
        ),
    ]
