# -*- coding: utf-8 -*-
# Generated by Django 4.2.22 on 2025-08-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ksvotes", "0008_earlyvotinglocationhours_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Election",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("election_date", models.DateField()),
                (
                    "election_type",
                    models.CharField(
                        choices=[("G", "General"), ("P", "Primary"), ("S", "Special")],
                        default="G",
                        max_length=1,
                    ),
                ),
                ("vr_deadline", models.DateField()),
                ("voting_start", models.DateField()),
                ("ab_deadline", models.DateField()),
                ("in_person_voting_start", models.DateField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
