# -*- coding: utf-8 -*-
# Generated by Django 4.2.30 on 2026-07-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ksvotes", "0009_alter_registrant_user_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrant",
            name="lang",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
