# -*- coding: utf-8 -*-
# Generated by Django 4.2.30 on 2026-07-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ksvotes", "0010_alter_registrant_lang"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrant",
            name="reg_lookup_time",
            field=models.FloatField(null=True),
        ),
    ]
